// <auto-generated />
using System;
using GreenBowl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GreenBowl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenBowl.Models.BCPaChecks", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("TimeOfCheck")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("SealingCondition")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Batch", "Lot", "TimeOfCheck");

                    b.ToTable("BCPaChecks");
                });

            modelBuilder.Entity("GreenBowl.Models.BCPrChecks", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("TimeOfCheck")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("XRayRejectedPouches")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Batch", "Lot", "TimeOfCheck");

                    b.ToTable("BCPrChecks");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCBS", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("IngredientLot")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<bool>("Allergens")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("AmountPerBatch")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("HygenicCondition")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("IngredientName")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Batch", "Lot", "IngredientLot");

                    b.HasIndex("IngredientLot");

                    b.HasIndex("Lot");

                    b.HasIndex("Batch", "Lot", "IngredientName")
                        .IsUnique();

                    b.ToTable("BatchBCBS");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCE", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("CIP_COPBeforeStarting")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Equipments")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(4000)");

                    b.Property<bool>("FunctionCondition")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("HygienicCondition")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("InitialOfController")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchBCEs");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPa", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FinishTimeFilling")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NoPrintRejected")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumberOfPouchMade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("PouchHygienicCondition")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("SealingRejected")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartTimeFilling")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("WeightRejected")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchBCPas");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPr", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Alarm")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CorrectionAction")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FinishTimeProcessing")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NumberOfRejectedPouch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Reason")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("StartTimeProcessing")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchBCPrs");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlBatchingStep", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ProductName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ProductionSupervisor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchingControlBatchingSteps");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlEquipment", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FillerSupervisor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchingControlEquipments");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlPackaging", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FillerSupervisor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TypeOfPackaging")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchingControlPackagings");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlProcessing", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ProductionSupervisor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("BatchingControlProcessings");
                });

            modelBuilder.Entity("GreenBowl.Models.BulgingTestOnPouch", b =>
                {
                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Comments")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateOfRelease")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NumberOfPouch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("QAInitial")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Results")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("TPC")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Taste")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("TemperatureOfIncubation")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TimeOfIncubation")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("YM")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Lot");

                    b.ToTable("BulgingTestOnPouches");
                });

            modelBuilder.Entity("GreenBowl.Models.InboundTrailer", b =>
                {
                    b.Property<string>("IngredientLot")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<bool>("QualityCheck")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TruckPlate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IngredientLot");

                    b.ToTable("InboundTrailers");
                });

            modelBuilder.Entity("GreenBowl.Models.IngredientsInventory", b =>
                {
                    b.Property<string>("IngredientLot")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("IngredientName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IngredientLot");

                    b.ToTable("IngredientsInventories");
                });

            modelBuilder.Entity("GreenBowl.Models.ProductInventory", b =>
                {
                    b.Property<int>("Lot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lot"));

                    b.Property<int>("ActualInventory")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("BatchWeight")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("CartonDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NoPrint")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Pouch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductForSale")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Productivity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("QACheck")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("QCRetention")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Sample")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SealingRejected")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalCase")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalRejected")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("WeightRejected")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("XRayRejected")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Lot");

                    b.ToTable("ProductInventories");
                });

            modelBuilder.Entity("GreenBowl.Models.Receipt", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("SellingDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("ID");

                    b.HasIndex("Lot");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("GreenBowl.Models.XRayMonitoringRecord", b =>
                {
                    b.Property<int>("Batch")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Lot")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Deviation_CorrectiveAction")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("Indicator1")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Indicator2")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("Indicator3")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("ProductName")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Batch", "Lot");

                    b.HasIndex("Lot");

                    b.ToTable("XRayMonitoringRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenBowl.Models.BCPaChecks", b =>
                {
                    b.HasOne("GreenBowl.Models.BatchBCPa", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BCPrChecks", b =>
                {
                    b.HasOne("GreenBowl.Models.BatchBCPr", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCBS", b =>
                {
                    b.HasOne("GreenBowl.Models.IngredientsInventory", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientLot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenBowl.Models.BatchingControlBatchingStep", "Parent")
                        .WithMany("Child")
                        .HasForeignKey("Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCE", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenBowl.Models.BatchingControlEquipment", "Parent")
                        .WithOne("Child")
                        .HasForeignKey("GreenBowl.Models.BatchBCE", "Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPa", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenBowl.Models.BatchingControlPackaging", "Parent")
                        .WithOne("Child")
                        .HasForeignKey("GreenBowl.Models.BatchBCPa", "Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPr", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenBowl.Models.BatchingControlProcessing", "Parent")
                        .WithOne("Child")
                        .HasForeignKey("GreenBowl.Models.BatchBCPr", "Batch", "Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlBatchingStep", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlEquipment", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlPackaging", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlProcessing", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.BulgingTestOnPouch", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.InboundTrailer", b =>
                {
                    b.HasOne("GreenBowl.Models.IngredientsInventory", null)
                        .WithOne()
                        .HasForeignKey("GreenBowl.Models.InboundTrailer", "IngredientLot")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.Receipt", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.XRayMonitoringRecord", b =>
                {
                    b.HasOne("GreenBowl.Models.ProductInventory", null)
                        .WithMany()
                        .HasForeignKey("Lot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPa", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchBCPr", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlBatchingStep", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlEquipment", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlPackaging", b =>
                {
                    b.Navigation("Child");
                });

            modelBuilder.Entity("GreenBowl.Models.BatchingControlProcessing", b =>
                {
                    b.Navigation("Child");
                });
#pragma warning restore 612, 618
        }
    }
}
